[versions]
javapoet = "1.13.0"
micronaut = "4.0.0"
micronaut-logging = "1.0.0"
micronaut-picocli = "5.0.1"
micronaut-test = "4.0.0"

[libraries]
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
micronaut-logging = { module = "io.micronaut.logging:micronaut-logging-bom", version.ref = "micronaut-logging" }
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }
micronaut-picocli = { module = "io.micronaut.picocli:micronaut-picocli-bom", version.ref = "micronaut-picocli" }
